#PyJ2D - Copyright (C) 2011 James Garnon <http://gatc.ca/>
#Released under the MIT License <http://opensource.org/licenses/MIT>

"""
java.awt.Cursor API
http://docs.oracle.com/javase/7/docs/api/java/awt/Cursor.html

TYPES = [DEFAULT_CURSOR, CROSSHAIR_CURSOR, E_RESIZE_CURSOR, HAND_CURSOR,
MOVE_CURSOR, N_RESIZE_CURSOR, NE_RESIZE_CURSOR, NW_RESIZE_CURSOR,
S_RESIZE_CURSOR, SE_RESIZE_CURSOR, SW_RESIZE_CURSOR, TEXT_CURSOR,
W_RESIZE_CURSOR, WAIT_CURSOR, CUSTOM_CURSOR]
"""

from java.awt import Cursor


DEFAULT_CURSOR = Cursor.DEFAULT_CURSOR
CROSSHAIR_CURSOR = Cursor.CROSSHAIR_CURSOR
E_RESIZE_CURSOR = Cursor.E_RESIZE_CURSOR
HAND_CURSOR = Cursor.HAND_CURSOR
MOVE_CURSOR = Cursor.MOVE_CURSOR
N_RESIZE_CURSOR = Cursor.N_RESIZE_CURSOR
NE_RESIZE_CURSOR = Cursor.NE_RESIZE_CURSOR
NW_RESIZE_CURSOR = Cursor.NW_RESIZE_CURSOR
S_RESIZE_CURSOR = Cursor.S_RESIZE_CURSOR
SE_RESIZE_CURSOR = Cursor.SE_RESIZE_CURSOR
SW_RESIZE_CURSOR = Cursor.SW_RESIZE_CURSOR
TEXT_CURSOR = Cursor.TEXT_CURSOR
W_RESIZE_CURSOR = Cursor.W_RESIZE_CURSOR
WAIT_CURSOR = Cursor.WAIT_CURSOR
CUSTOM_CURSOR = Cursor.CUSTOM_CURSOR

#cursors not implemented
arrow = diamond = broken_x = tri_left = tri_right = ()

